language: go

go:
    - 1.4
    - 1.5
    - 1.6
    - tip

script:
    - go test -v ./...

install:
    - go get github.com/PuerkitoBio/goquery
    - go get github.com/nladuo/go-zk-lock
    - go get github.com/samuel/go-zookeeper/zk
    - go get github.com/jinzhu/gorm 
    - go get github.com/lib/pq
    - go get github.com/Go-SQL-Driver/MySQL